# Site settings.

# Without a clear rule enforced, both title and name are used.
title: µOS++ IIIe / CMSIS++
name: µOS++ IIIe / CMSIS++
description: The third edition of µOS++ and CMSIS++, a proposal for the next generation CMSIS, written in C++.
motto: “Perfekt ist nicht gut genug”
icon: wall-e-icon.png

email: ilg@livius.net

destination: _site
exclude:
  - README.md
  - jekyll-serve.command
  - jekyll-build.command
  - atom.command
  - localhost-4001.webloc
  - '*.pptx'
  - .github

# Used in sitemap.xml.
url: "http://micro-os-plus.github.io" # the base hostname & protocol for your site.

# The subpath of your site, e.g. /blog (note the leading slash and the
# absence of a trailing slash).
baseurl: ""

# This timezone is used to display post dates and last modified messages.
timezone: UTC

encoding: utf-8

# Default permalink used for posts.
permalink: /blog/:year/:month/:day/:title/

# Build settings.
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Warning: paginator retired in Jekyll 3!
# Make this larger, probably 5 is a good choice.
# paginate: 2
# paginate_path: "/blog/page:num/"

# The number of links added to the 'Latest news' box.
latest-news-pages: 4

# Currently disabled, since it generates incomplete content.
# Use manually written RSS feed.xml.
#   - jekyll-feed
# {% feed_meta %} in head.html

# jekyll-last-modified-at is not available on GitHub Pages.
gems:
  - jekyll-last-modified-at
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

# Custom definitions.

# References to the project associated with the web.
github-username:  ilg-ul
github-project-name: micro-os-plus/cmsis-plus
github-project-url: http://github.com/micro-os-plus/cmsis-plus
sourceforge-project-url: http://sourceforge.net/projects/micro-os-plus

# Change it to refer to project's page
# facebook-url: https://facebook.com/ilg-ul/
facebook-page: https://facebook.com/microosplus/

# twitter-url: http://twitter.com/ilegeul

# If you have one, define it here.
google-analytics-id: UA-16767008-14
google-site-verification: NT_y3tqI_8mrd8gYA_FDWHT2-tkJExOC6KBkSnyZx6c

# Disable it if no site footer is needed.
# custom-footer-content: content/site-custom-footer.markdown

# jekyll-toc-generator
tocTopTag: h2
minItemsToShowToc: 3
useExistingAnchors: true

css-date: 201603032012

# Content copyright. Update it to your needs.
copyright-message: "© 2016 Liviu Ionescu"
